### ISSUE TITLE
文本显示问题

### ISSUE THREAD

**Issue by ncnnnnn** [soarqin/HeroesOfJinYong#2]
1、在data/font放了个otf字体文件
2、进入游戏第一个菜单，没文本显示

TTF::render 可以打印出文本：“请输入姓名”

好像基本都在 fontCache_ continue了，没有进入绘制。
而偶尔后续renderTexture也没绘制出文本。

不知道是哪里的问题。。。

**Comment by soarqin** [comment]
如果配置文件没写错的话，有可能是stb_truetype不支持的otf字体，试试切换freetype的实现

**Comment by ncnnnnn** [comment]
原来随便放了个 FontAwesome.otf
改成中文ttf可以了。
